- hosts: localhost
  connection: local
  
  tasks:
  - name: Create & Start Container
    docker_container:
      name: myweb
      image: "normalboot/hello-world:v1"
      state: started
      ports:
      - "80:8080"